- name: install packages
  become: true
  apt: name={{item}} state=installed
  with_items:
    - squid
    - stunnel
- name: stunnel configuration
  become: true
  template:
    src: stunnel.conf.j2
    dest: '{{ stunnel.conf }}'
  notify:
    - reload stunnel
- name: squid minimum configuration
  replace:
    dest: '{{ squid.conf }}'
    regexp: '#acl (localnet|SSL_ports|Safe_ports)'
    replace: 'acl \1'
    backup: yes
- name: squid include acl config
  become: true
  lineinfile:
    dest: '{{ squid.conf }}'
    insertbefore: '#  TAG: acl'
    line: include {{ squid.acl_conf }}
  notify:
    - reload squid
- name: squid acl config
  become: true
  template:
    src: squid.acl.config.j2
    dest: '{{ squid.acl_conf }}'
  notify:
    - reload squid
