stunnel:
  conf: /etc/stunnel/stunnel.conf
  port: 443
  debug: 7
  verify: 4
squid:
  conf: /etc/squid3/squid.conf
  acl_conf: /etc/squid3/squid.acl.config
  acl:
    - { port: 22, comment: ssh }
    - { port: 6697, comment: IRC Secure }
    - { port: 29418, comment: gerrit }
